/* Generated by course/build_course.py from content_en.py -- do not edit. */
window.DECK_CONTENT = {
 "lang": "en",
 "deckTitle": "Quantum Transport with Kwant",
 "sections": {
  "opening": "Opening",
  "lattice": "From Schrödinger to a lattice",
  "leads": "Leads and conductance",
  "shapes": "Shapes, potentials, parameters",
  "spin-graphene-sc": "Spin, graphene, superconductors",
  "magnetic": "Magnetic fields",
  "toolbox": "Toolbox",
  "topo1d": "Topology in one dimension",
  "topo2d3d": "Topology in two and three dimensions",
  "close": "Close"
 },
 "slides": {
  "cold-open": {
   "kicker": "An undergraduate course · one executed notebook",
   "title": "Quantum Transport with Kwant",
   "sub": "From the Schrödinger equation to topological matter, with the code that computes it",
   "notes": "Open with the object on the table: a wire a few hundred nanometres wide, colder than deep space, and a current that comes in exact steps. Nothing about it is classical. The promise of the course: every picture on these slides was computed by a notebook you can run yourself in a few minutes, and every equation is one you will be able to type into Kwant by the end. No result is shown that the notebook does not check. Q: \"Do I need to know Python?\" A: you need to read it; the notebook is the textbook."
  },
  "what-is-transport": {
   "title": "What quantum transport asks",
   "lead": "Attach wires to a small quantum object and push a current through it. How much gets through, and why?",
   "b1": "<strong>Classical wire:</strong> resistance grows with length, current is a smooth function of voltage.",
   "b2": "<strong>Quantum wire:</strong> the conductance comes in <em>steps</em> of <span class=\"math\">e<sup>2</sup>/h</span> and can be <em>higher</em> with a barrier than without — interference decides.",
   "b3": "The question turns into a scattering problem: an electron wave comes in through a lead, the device scatters it, and the current is the probability of getting through.",
   "b4": "A computer is needed because devices have thousands of atoms, disorder, spin, magnetic fields — but the physics is one equation, and one lattice code solves it exactly.",
   "notes": "Set the two contrasts: length dependence (Ohm) versus steps; and the surprise that a barrier can raise conductance through resonance. Then reframe as scattering: leads are waveguides, the device is the scatterer, transmission is conductance. That is the whole Landauer picture in one sentence; the mathematics comes in section 2. Q: \"Why not solve the Schrödinger equation directly?\" A: you do — on a lattice, where it is a sparse matrix; that is what Kwant does."
  },
  "course-map": {
   "title": "The course in ten stops",
   "lead": "The stops follow each other in order; inside each one the slides go from words to code to equations.",
   "thead": "<th>Stop</th><th>Physics</th><th>Kwant</th>",
   "row1": "<td>1 Lattice</td><td>Schrödinger → tight binding</td><td>Builder, lattices, hoppings</td>",
   "row2": "<td>2 Leads</td><td>Landauer–Büttiker, Fisher–Lee</td><td>attach_lead, smatrix</td>",
   "row3": "<td>3 Shapes</td><td>resonances, billiards, parameters</td><td>shape functions, value functions</td>",
   "row4": "<td>4 Spin · graphene · SC</td><td>Rashba, Dirac cones, Andreev</td><td>matrix values, honeycomb, BdG</td>",
   "row5": "<td>5 Magnetic fields</td><td>Peierls phase, Landau levels, Hofstadter</td><td>phase hoppings, wraparound</td>",
   "row6": "<td>6 Toolbox</td><td>KPM, continuum models, solvers, pitfalls</td><td>kpm, continuum, MUMPS vs SuperLU</td>",
   "row7": "<td>7 Topology in 1D</td><td>SSH, Kitaev, Majoranas, pumps</td><td>invariants from the system</td>",
   "row8": "<td>8 Topology in 2D/3D</td><td>Chern, Z<sub>2</sub>, chiral Majoranas, corners, Weyl, 3D TI</td><td>Berry curvature on a torus</td>",
   "row9": "<td>9 Close</td><td>how to run it, exercises, reading</td><td>Run All</td>",
   "notes": "Read the map once, quickly. Tell the audience which stops you will take at depth today and which you will pass through — the maths and the extra figure pages of a stop can be skipped forward without losing the thread. Stops 7 and 8 are the second half of the notebook (Part II) and can be a separate lecture. Q: \"Which stops need the most maths?\" A: 2, 5 and 7–8; each has its maths near the end of the section."
  },
  "part-lattice": {
   "kicker": "Part 2 of 10",
   "title": "From Schrödinger to a lattice",
   "sub": "Show that discretising the Schrödinger equation gives a hopping model, and that Kwant's Builder is exactly that model written down.",
   "ag1": "Put the wavefunction on a grid",
   "ag2": "The discretisation, done honestly",
   "ag3": "Kwant's Builder is the Hamiltonian, written as a dictionary",
   "ag4": "Figure 1 · The object model",
   "ag5": "Figure 3 · The object model",
   "ag6": "The vocabulary you will use every day",
   "notes": "Section opener. Show that discretising the Schrödinger equation gives a hopping model, and that Kwant's Builder is exactly that model written down. The agenda colours say what each slide is: plain language (grey), a figure (green), Kwant code (blue), the mathematics (pink). Say in one sentence where this stop sits on the course map, then move on."
  },
  "why-lattice": {
   "title": "Put the wavefunction on a grid",
   "lead": "Replace space by a lattice of sites. The kinetic energy becomes a rule: an electron hops to its neighbours.",
   "b1": "Each site carries an <strong>on-site energy</strong>; each bond carries a <strong>hopping</strong> amplitude <span class=\"math\">t</span>.",
   "b2": "A finer grid means a better approximation to the continuum — and more sites to solve for.",
   "b3": "Real crystals <em>are</em> lattices: for graphene or a chain of atoms the model is not an approximation at all.",
   "b4": "Everything else in the course — leads, spin, magnetic fields, superconductivity — is a choice of what sits on the sites and the bonds.",
   "notes": "The figure is the notebook's 5×5 square lattice with every nearest-neighbour bond drawn. Make the two readings explicit: (1) the grid is a numerical discretisation of a continuum; (2) the grid is a real crystal. Kwant does not care which. The bond picture is the mental model for the whole course: numbers on dots, numbers on lines. Q: \"How fine must the grid be?\" A: fine enough that the wavelength spans many sites — the next slide gives the number."
  },
  "discretise": {
   "title": "The discretisation, done honestly",
   "lead": "Finite differences on a grid of spacing a turn the Laplacian into hopping.",
   "b1": "The lattice reproduces the free particle for <span class=\"math\">ka ≪ 1</span>; at the band edge it is a different (but perfectly legitimate) crystal.",
   "b2": "Sign convention: hoppings are <span class=\"math\">−t</span>; the on-site <span class=\"math\">4t</span> puts the band bottom at zero. Kwant lets you choose; the notebook keeps this one.",
   "eqlabel1": "Continuum",
   "eq1": "<span class=\"math\">H = −(ħ<sup>2</sup>/2m) ∇<sup>2</sup> + V(<b>r</b>)</span>",
   "eqlabel2": "Second derivative on a grid",
   "eq2": "<span class=\"math\">ψ″(x) ≈ [ψ(x+a) − 2ψ(x) + ψ(x−a)] / a<sup>2</sup></span>",
   "eqlabel3": "Hopping and on-site energy (2D)",
   "eq3": "<span class=\"math\">t = ħ<sup>2</sup>/(2ma<sup>2</sup>),   ε<sub>i</sub> = 4t + V(<b>r</b><sub>i</sub>)</span>",
   "eqlabel4": "Tight-binding Hamiltonian",
   "eq4": "<span class=\"math\">H = Σ<sub>i</sub> ε<sub>i</sub> |i⟩⟨i| − t Σ<sub>⟨ij⟩</sub> (|i⟩⟨j| + h.c.)</span>",
   "eqlabel5": "Band of the empty lattice",
   "eq5": "<span class=\"math\">E(<b>k</b>) = 4t − 2t(cos k<sub>x</sub>a + cos k<sub>y</sub>a) ≈ ħ<sup>2</sup>k<sup>2</sup>/2m</span>",
   "notes": "Derive the second-difference formula on the board in one line; the rest follows. The key numbers: t sets the energy scale, 4t (in 2D; 2t in 1D, 6t in 3D) is the band width divided by two. The dispersion at the bottom of the band is quadratic with the right mass — that is the check that the lattice is the continuum. Q: \"Where did ħ and m go in the notebook?\" A: into t = 1; every energy is in units of t and every length in units of a."
  },
  "builder": {
   "title": "Kwant's Builder is the Hamiltonian, written as a dictionary",
   "lead": "Sites and hoppings are keys; the numbers (or functions) on them are the values.",
   "b1": "<code>lat(x, y)</code> is a <strong>Site</strong>: a lattice plus integer coordinates.",
   "b2": "<code>lat.neighbors()</code> is a <strong>HoppingKind</strong>: 'all bonds of this shape'; <code>lat.neighbors(2)</code> adds the diagonals.",
   "b3": "Values may be numbers, matrices (spin!) or <em>functions</em> of the site and of runtime parameters.",
   "b4": "<code>finalized()</code> turns the dictionary into the matrices the solvers use. Nothing is computed before.",
   "code": "import kwant\nlat = kwant.lattice.square(a=1, norbs=1)\nsyst = kwant.Builder()\nfor x in range(30):\n    for y in range(10):\n        syst[lat(x, y)] = 4 * t          # on-site energy\nsyst[lat.neighbors()] = -t           # every nearest-neighbour bond\nfsyst = syst.finalized()             # freeze -&gt; sparse matrices\n",
   "notes": "Type it live if you can. The Builder is literally a mapping: site → on-site value, (site, site) → hopping. Stress the three kinds of value (number, matrix, function) — each later section is one of them. Finalisation is the moment the lazy description becomes numbers; leads get attached before it. Q: \"What does norbs do?\" A: the number of orbitals per site — 1 here, 2 for spin, 4 for spinful superconductors; Kwant needs it to interpret matrix values and to compute densities."
  },
  "figpage-01": {
   "title": "Figure 1 · The object model",
   "notes": "Figure 1 of the notebook (cell 6). A 5x5 square-lattice Builder with only horizontal bonds, added via the explicit HoppingKind (1,0)."
  },
  "figpage-03": {
   "title": "Figure 3 · The object model",
   "notes": "Figure 3 of the notebook (cell 6). lat.neighbors(2) adds the diagonal second-neighbour bonds on top."
  },
  "object-model": {
   "title": "The vocabulary you will use every day",
   "lead": "Six objects; everything in the course is built from them.",
   "thead": "<th>Object</th><th>What it is</th><th>Typical line</th>",
   "row1": "<td><code>Lattice</code></td><td>the geometry: unit vectors + basis</td><td><code>kwant.lattice.honeycomb()</code></td>",
   "row2": "<td><code>Site</code></td><td>a lattice plus a tag (integer coordinates)</td><td><code>lat(3, 4)</code></td>",
   "row3": "<td><code>Builder</code></td><td>the mutable Hamiltonian: sites → values, bonds → values</td><td><code>syst[lat(0, 0)] = 4*t</code></td>",
   "row4": "<td><code>HoppingKind</code></td><td>a family of bonds by displacement</td><td><code>kwant.builder.HoppingKind((1, 0), lat)</code></td>",
   "row5": "<td>lead</td><td>a Builder with a translational symmetry, repeated to infinity</td><td><code>syst.attach_lead(lead)</code></td>",
   "row6": "<td>finalized system</td><td>immutable, indexable, solvable</td><td><code>kwant.smatrix(fsyst, energy)</code></td>",
   "notes": "This table is the reference card; the handout repeats it. Two things people mix up: a Site is a key, not a number; a lead is not a wire of finite length but an infinite repetition of one unit cell along its symmetry. Q: \"Can a lead have a different lattice from the device?\" A: yes, as long as the sites at the interface match up — the graphene example does exactly that."
  },
  "part-leads": {
   "kicker": "Part 3 of 10",
   "title": "Leads and conductance",
   "sub": "Compute a first conductance, see it quantised, and derive why: Landauer–Büttiker and the Fisher–Lee relation.",
   "ag1": "The canonical experiment: a wire between two reservoirs",
   "ag2": "Conductance comes in steps",
   "ag3": "The Landauer–Büttiker formula and where Kwant gets it",
   "ag4": "See the modes: lead bands and a scattering state",
   "ag5": "Ten lines from geometry to conductance",
   "notes": "Section opener. Compute a first conductance, see it quantised, and derive why: Landauer–Büttiker and the Fisher–Lee relation. The agenda colours say what each slide is: plain language (grey), a figure (green), Kwant code (blue), the mathematics (pink). Say in one sentence where this stop sits on the course map, then move on."
  },
  "two-terminal": {
   "title": "The canonical experiment: a wire between two reservoirs",
   "lead": "A finite scattering region (blue) with two semi-infinite leads (red). Electrons come in from one side and leave through either.",
   "b1": "Leads are perfect waveguides: translationally invariant, so their states are Bloch waves with a band structure <span class=\"math\">E<sub>n</sub>(k)</span>.",
   "b2": "At a given energy each lead carries a finite number <span class=\"math\">N</span> of <strong>propagating modes</strong>.",
   "b3": "The device mixes them; the scattering matrix records the outcome.",
   "notes": "The figure is the notebook's W=10, L=30 wire, drawn by kwant.plot. Point at the lead unit cell being repeated. Introduce 'mode' as 'a transverse standing wave that also travels along the lead'. Q: \"Where is the voltage?\" A: in the reservoirs the leads end in — they fix the occupation of incoming modes; the leads themselves are ideal."
  },
  "quantised": {
   "title": "Conductance comes in steps",
   "lead": "Sweep the energy: every time a new subband opens in the lead, the conductance rises by exactly one unit.",
   "b1": "Step height <span class=\"math\">e<sup>2</sup>/h</span> for spinless electrons (<span class=\"math\">2e<sup>2</sup>/h</span> with spin) — a universal constant, no material parameter in it.",
   "b2": "A clean wire transmits every open mode perfectly: <span class=\"math\">G = (e<sup>2</sup>/h) · N(E)</span>.",
   "b3": "First seen in a quantum point contact in 1988 (van Wees; Wharam); this figure is that experiment computed.",
   "notes": "This is the first result the audience should be able to reproduce from the notebook. Ask them to count the steps and compare with the subband minima on the band-structure slide two slides ahead. Emphasise the universality: the step is a ratio of fundamental constants. Q: \"Why is it not infinite for a perfect conductor?\" A: the contact resistance — connecting a lead with finitely many modes to a reservoir costs h/e² per mode, however perfect the wire."
  },
  "landauer": {
   "title": "The Landauer–Büttiker formula and where Kwant gets it",
   "lead": "Conductance is transmission. The transmission comes from the Green's function of the device.",
   "b1": "Kwant solves a sparse linear system of the size of the device once per energy; the leads enter only through their self-energy, computed from their unit cell.",
   "b2": "Unitarity and the sum rule are exact identities — the notebook asserts them after every calculation, and so should you.",
   "eqlabel1": "Landauer",
   "eq1": "<span class=\"math\">G = (e<sup>2</sup>/h) Σ<sub>n</sub> T<sub>n</sub> = (e<sup>2</sup>/h) Tr(t<sup>†</sup>t)</span>",
   "eqlabel2": "Scattering matrix",
   "eq2": "<span class=\"math\">S = </span>[[r, t′], [t, r′]]<span class=\"math\">,   S<sup>†</sup>S = 1</span>",
   "eqlabel3": "Fisher–Lee",
   "eq3": "<span class=\"math\">S = −1 + i Γ<sup>1/2</sup> G<sup>r</sup>(E) Γ<sup>1/2</sup>,   G<sup>r</sup> = (E − H − Σ)<sup>−1</sup></span>",
   "eqlabel4": "Lead self-energy",
   "eq4": "<span class=\"math\">Σ(E) = Σ<sub>leads</sub> V<sup>†</sup> g<sub>lead</sub>(E) V,   Γ = i(Σ − Σ<sup>†</sup>)</span>",
   "eqlabel5": "Sum rule",
   "eq5": "<span class=\"math\">Σ<sub>n</sub> (T<sub>n</sub> + R<sub>n</sub>) = N</span> — current conservation",
   "notes": "Derivation sketch on the board: incoming flux in mode n is e/h per unit energy; the fraction T_n gets through; sum and multiply by e for the current. Then say what Kwant does: it never builds the infinite leads, it folds them into a boundary condition (the self-energy) and solves a finite sparse problem. Q: \"Is this only linear response?\" A: yes — G at fixed E; a finite bias is an integral of T(E) between the two chemical potentials."
  },
  "modes": {
   "title": "See the modes: lead bands and a scattering state",
   "lead": "The staircase is the lead's subband structure; a scattering state is one incoming mode plus everything it becomes.",
   "b1": "Each subband minimum <span class=\"math\">E<sub>n</sub></span> opens one channel: transverse quantisation in a strip of width <span class=\"math\">W</span> gives <span class=\"math\">E<sub>n</sub> ≈ 2t[1 − cos(nπ/(W+1))]</span>.",
   "b2": "The scattering state is a standing wave across the wire and a travelling wave along it — with the density pattern of the mode it came from.",
   "notes": "Left: kwant.physics.Bands of the lead — compare each minimum with a step of the staircase. Right: kwant.wave_function at E = 0.6 for the lowest mode from the left; the density shows the transverse node structure. Q: \"What happens at a band maximum?\" A: modes close again — the staircase comes back down at the top of the band; on a lattice the band is finite."
  },
  "code-smatrix": {
   "title": "Ten lines from geometry to conductance",
   "lead": "Attach leads, finalise, ask for the scattering matrix.",
   "b1": "The lead is a Builder with a <code>TranslationalSymmetry</code>; <code>attach_lead</code> finds the interface sites.",
   "b2": "<code>smatrix</code> returns the full <span class=\"math\">S</span>; <code>transmission(1, 0)</code> sums <span class=\"math\">T<sub>n</sub></span> from lead 0 into lead 1.",
   "b3": "The last line is the sum rule as an <code>assert</code>: the notebook's habit of checking every result.",
   "code": "lead = kwant.Builder(kwant.TranslationalSymmetry((-1, 0)))\nlead[(lat(0, y) for y in range(W))] = 4 * t\nlead[lat.neighbors()] = -t\nsyst.attach_lead(lead)                 # left\nsyst.attach_lead(lead.reversed())      # right\nfsyst = syst.finalized()\n\nsm = kwant.smatrix(fsyst, energy=0.5)\nG = sm.transmission(1, 0)              # e^2/h units\nassert abs(sm.transmission(0, 0) + G - sm.num_propagating(0)) &lt; 1e-10\n",
   "notes": "Walk the code top to bottom. lead.reversed() flips the symmetry direction for the right lead. Point out that the assert is not decoration: it catches a wrong lead, a wrong energy inside a gap, a broken build. Q: \"How long does this take?\" A: milliseconds for 300 sites; the solver section shows the scaling."
  },
  "part-shapes": {
   "kicker": "Part 4 of 10",
   "title": "Shapes, potentials, parameters",
   "sub": "Make the device interesting: potentials that vary in space, arbitrary shapes, and parameters changed at solve time.",
   "ag1": "A potential well makes resonances",
   "ag2": "Any shape you can write as a function",
   "ag3": "Parameters at solve time, not at build time",
   "notes": "Section opener. Make the device interesting: potentials that vary in space, arbitrary shapes, and parameters changed at solve time. The agenda colours say what each slide is: plain language (grey), a figure (green), Kwant code (blue), the mathematics (pink). Say in one sentence where this stop sits on the course map, then move on."
  },
  "well": {
   "title": "A potential well makes resonances",
   "lead": "Lower the on-site energy in a stretch of the wire and the transmission acquires sharp peaks: quasi-bound states.",
   "b1": "The well is a cavity; an electron bounces between its ends like light in a Fabry–Pérot etalon.",
   "b2": "Constructive interference at the quasi-bound energies gives <span class=\"math\">T → 1</span> peaks; in between, reflection.",
   "b3": "In Kwant the potential is just a <em>function of the site</em> assigned as the on-site value.",
   "notes": "Connect to optics explicitly; students know Fabry–Pérot. The peak positions move with the well depth and length — a good exercise (the notebook has one). Q: \"Why are the peaks not delta functions?\" A: the states leak into the leads; the width is the inverse lifetime, ħ/τ."
  },
  "stadium": {
   "title": "Any shape you can write as a function",
   "lead": "A shape is a predicate on coordinates. The stadium is the classic chaotic billiard; its eigenstates are 'scars' on classical orbits.",
   "b1": "<code>lat.shape(stadium, start)</code> floods the lattice from a start site, keeping every site where the predicate is true.",
   "b2": "Closed systems have no leads: diagonalise <code>fsyst.hamiltonian_submatrix(sparse=True)</code> with <code>scipy.sparse.linalg.eigsh</code>.",
   "b3": "Chaotic billiards are the playground of random-matrix theory: level statistics, scarring, weak localisation.",
   "notes": "The stadium is two half-discs joined by a rectangle; the function is three lines. Show the eigenstate and ask what a classical billiard ball would do — the 'scar' is a quantum memory of an unstable periodic orbit. Q: \"Why sparse?\" A: the Hamiltonian has ~5 non-zeros per row; a dense matrix for 10⁴ sites would be 800 MB, the sparse one is a few MB."
  },
  "params": {
   "title": "Parameters at solve time, not at build time",
   "lead": "Values can be functions whose extra arguments are supplied when you solve — sweep a field without rebuilding.",
   "b1": "The function's first argument is the site (or two sites for a hopping); the rest are named parameters.",
   "b2": "<code>params=</code> passes them at solve time; the finalized system is built once.",
   "b3": "This is how every sweep in the course works: energy, field, chemical potential, pairing, dimerisation.",
   "code": "def onsite(site, V0, x0):\n    x, y = site.pos\n    return 4 * t + (V0 if abs(x - x0) &lt; 5 else 0)\n\nsyst[(lat(x, y) for x in range(L) for y in range(W))] = onsite\nfsyst = syst.finalized()\n\nfor V0 in np.linspace(-1, 1, 41):\n    sm = kwant.smatrix(fsyst, energy=0.5, params=dict(V0=V0, x0=15))\n",
   "notes": "Emphasise the separation: geometry once, physics per call. Names matter — Kwant inspects the function signature to know which parameters it needs, so a typo shows up as a clear error. Q: \"Can I pass arrays?\" A: anything hashable-or-not; Kwant only forwards it. The magnetic-field section passes a float, the KPM section passes a callable."
  },
  "part-spin-graphene-sc": {
   "kicker": "Part 5 of 10",
   "title": "Spin, graphene, superconductors",
   "sub": "Show the three ways to enrich a site: matrix values (spin), other lattices (graphene), particle-hole doubling (BdG).",
   "ag1": "Spin: matrix values on sites and bonds",
   "ag2": "Graphene: a honeycomb lattice and a p–n junction",
   "ag3": "Figure 15 · Beyond square lattices — graphene",
   "ag4": "Superconductors: double the space, get Andreev reflection",
   "ag5": "The BdG construction and the conductance of an N–S junction",
   "ag6": "Local observables: where the current flows",
   "notes": "Section opener. Show the three ways to enrich a site: matrix values (spin), other lattices (graphene), particle-hole doubling (BdG). The agenda colours say what each slide is: plain language (grey), a figure (green), Kwant code (blue), the mathematics (pink). Say in one sentence where this stop sits on the course map, then move on."
  },
  "rashba": {
   "title": "Spin: matrix values on sites and bonds",
   "lead": "Two orbitals per site. Rashba spin–orbit coupling is a spin-dependent hopping; a Zeeman field is a spin-dependent on-site term.",
   "b1": "<span class=\"math\">H = −t Σ (c<sup>†</sup><sub>i</sub>c<sub>j</sub>) − iα Σ c<sup>†</sup><sub>i</sub>(<b>σ</b>×<b>d</b><sub>ij</sub>)<sub>z</sub> c<sub>j</sub> + B Σ c<sup>†</sup><sub>i</sub>σ<sub>z</sub>c<sub>i</sub></span>",
   "b2": "Rashba splits the subbands in <span class=\"math\">k</span>; Zeeman opens a <strong>helical gap</strong> at <span class=\"math\">k = 0</span> where only one spin direction propagates each way.",
   "b3": "The conductance staircase becomes non-monotonic: a plateau at an odd number of modes signals the helical gap.",
   "notes": "The hopping is a 2×2 matrix that depends on the bond direction — Kwant's HoppingKind gives you (1,0) and (0,1) separately, so the σ×d term is two lines. The helical gap is the ingredient of the Majorana nanowire in section 7; plant that now. Q: \"Why does the plateau go down?\" A: inside the helical gap one subband is missing at k = 0 — fewer modes at that energy than just above or below."
  },
  "graphene": {
   "title": "Graphene: a honeycomb lattice and a p–n junction",
   "lead": "Two sublattices, a linear 'Dirac' dispersion, and Klein tunnelling: at normal incidence a p–n junction is transparent.",
   "b1": "<code>kwant.lattice.honeycomb()</code> has a two-site basis; <code>lat.sublattices</code> gives A and B.",
   "b2": "A smooth potential step <span class=\"math\">V(x)</span> puts the Fermi level in the conduction band on one side and the valence band on the other.",
   "b3": "Transmission is suppressed near the Dirac point and revives above it — the notebook's ribbon leads show the folded Dirac cones (fig. 15).",
   "notes": "The figure on the left is a circular flake with two leads attached at 120°, sites coloured by sublattice — a good demonstration that leads may point in any lattice direction. Klein tunnelling is the headline: the chirality of the Dirac electron forbids backscattering at normal incidence. Q: \"Is graphene special for Kwant?\" A: no — it is one more lattice; the physics is in the geometry."
  },
  "figpage-15": {
   "title": "Figure 15 · Beyond square lattices — graphene",
   "notes": "Figure 15 of the notebook (cell 24). Subbands of the graphene nanoribbon lead: bulk Dirac cones folded into 1D bands."
  },
  "bdg": {
   "title": "Superconductors: double the space, get Andreev reflection",
   "lead": "Bogoliubov–de Gennes doubles every site into electron and hole. An electron hitting a superconductor can bounce back as a hole.",
   "b1": "Below the gap <span class=\"math\">Δ</span> no quasiparticle can enter the superconductor: the only channels are normal reflection and <strong>Andreev reflection</strong> (electron → hole, a Cooper pair enters).",
   "b2": "Perfect Andreev reflection doubles the conductance: <span class=\"math\">G = 2e<sup>2</sup>/h</span> per mode with no barrier.",
   "b3": "A tunnel barrier crosses over to the normal-state result — the Blonder–Tinkham–Klapwijk curves.",
   "notes": "The N–S junction figure shows normal region, barrier and superconductor; the conductance panel is BTK for several barrier strengths. The doubling is the key surprise: charge 2e crosses per event. Q: \"What is a hole here?\" A: the time-reversed electron state at −E; BdG treats it as a second particle type so that pairing becomes a hopping between the two."
  },
  "bdg-math": {
   "title": "The BdG construction and the conductance of an N–S junction",
   "lead": "Particle–hole symmetry is built in; the scattering matrix gets electron and hole blocks.",
   "b1": "In Kwant: <code>norbs=2</code> (or 4 with spin), on-site <span class=\"math\">τ<sub>z</sub>(ε − μ) + τ<sub>x</sub>Δ</span>, and <code>conservation_law=-τ<sub>z</sub></code> so <code>smatrix</code> can separate electron and hole blocks.",
   "b2": "The notebook checks particle–hole symmetry of the spectrum and the N–S sum rule explicitly.",
   "eqlabel1": "BdG Hamiltonian",
   "eq1": "<span class=\"math\">H<sub>BdG</sub> = </span>[[H − μ, Δ], [Δ<sup>*</sup>, −(H − μ)<sup>*</sup>]]",
   "eqlabel2": "Particle–hole symmetry",
   "eq2": "<span class=\"math\">P H<sub>BdG</sub> P<sup>−1</sup> = −H<sub>BdG</sub>,   P = τ<sub>x</sub> K</span>  ⇒ spectrum symmetric about zero",
   "eqlabel3": "Sub-gap conductance",
   "eq3": "<span class=\"math\">G = (e<sup>2</sup>/h) [N − R<sub>ee</sub> + R<sub>he</sub>]</span>",
   "eqlabel4": "Perfect Andreev",
   "eq4": "<span class=\"math\">R<sub>he</sub> = N, R<sub>ee</sub> = 0 ⇒ G = 2Ne<sup>2</sup>/h</span>",
   "notes": "Write the 2×2 block form and point out the minus sign and complex conjugate — that is where particle–hole symmetry comes from. The conductance formula is the Landauer formula with Andreev counted with a plus sign because a hole carries current the other way. Q: \"Why does Kwant need conservation_law?\" A: to label the lead modes as electron or hole so that transmission(1, 0) can be resolved into R_ee and R_he."
  },
  "observables": {
   "title": "Local observables: where the current flows",
   "lead": "Densities and currents of a scattering state, as operators applied to the wavefunction.",
   "b1": "<code>kwant.operator.Density(fsyst, σ)</code> and <code>kwant.operator.Current(fsyst, σ)</code> — with a matrix <span class=\"math\">σ</span> to resolve spin.",
   "b2": "The four panels are charge density, spin density, charge current and spin current of one scattering state in the Rashba wire.",
   "b3": "Current conservation on every site is another identity the notebook asserts.",
   "notes": "This is the bridge to experiments that image current (scanning gate, SQUID microscopy). Point at the spin current being non-zero where the charge current is smooth — spin–orbit coupling at work. Q: \"Is the current operator unique on a lattice?\" A: the bond current is; Kwant computes the current through each bond from the hopping matrix element."
  },
  "part-magnetic": {
   "kicker": "Part 6 of 10",
   "title": "Magnetic fields",
   "sub": "Put a magnetic field on the lattice with Peierls phases; see Landau levels, the Hofstadter butterfly and a topological phase transition.",
   "ag1": "A magnetic field is a phase on every bond",
   "ag2": "Figure 13 · Band structure and closed systems",
   "ag3": "Peierls, Harper, and the flux quantum",
   "ag4": "The Hofstadter butterfly",
   "ag5": "Figure 31 · Magnetic fields — Peierls substitution and Landau levels",
   "ag6": "A field can switch a topological phase off",
   "notes": "Section opener. Put a magnetic field on the lattice with Peierls phases; see Landau levels, the Hofstadter butterfly and a topological phase transition. The agenda colours say what each slide is: plain language (grey), a figure (green), Kwant code (blue), the mathematics (pink). Say in one sentence where this stop sits on the course map, then move on."
  },
  "peierls": {
   "title": "A magnetic field is a phase on every bond",
   "lead": "Minimal coupling on a lattice: multiply each hopping by the phase of the vector potential integrated along the bond.",
   "b1": "Landau gauge <span class=\"math\"><b>A</b> = (−By, 0)</span>: horizontal bonds pick up <span class=\"math\">exp(−2πi Φ y/Φ<sub>0</sub>)</span>.",
   "b2": "The wire bands develop flat pieces: <strong>Landau levels</strong> in the bulk, dispersive <strong>edge states</strong> at the boundaries.",
   "b3": "The dashed lines are the exact continuum Landau levels <span class=\"math\">ħω<sub>c</sub>(n + ½)</span> — the lattice hits them at low field.",
   "notes": "Peierls substitution is the whole story: the phase around a plaquette is 2π times the flux through it in units of the flux quantum. The figure compares the lattice with the continuum — a validation the notebook performs numerically. Q: \"Which gauge should I use?\" A: any; only the flux per plaquette is physical. But a lead must be translationally invariant, so the gauge must respect its symmetry — the Landau gauge with the lead along x does."
  },
  "figpage-13": {
   "title": "Figure 13 · Band structure and closed systems",
   "notes": "Figure 13 of the notebook (cell 21). Spectrum of a closed disc vs magnetic field: levels condense into degenerate Landau levels (a Fock-Darwin-like fan)."
  },
  "peierls-math": {
   "title": "Peierls, Harper, and the flux quantum",
   "lead": "The phase per bond, the phase per plaquette, and the 1D equation that hides the butterfly.",
   "b1": "Every one of Kwant's magnetic-field examples is this substitution with a different <span class=\"math\"><b>A</b></span>.",
   "b2": "For a periodic system use <code>kwant.wraparound</code> to turn a symmetry into a momentum parameter.",
   "eqlabel1": "Peierls phase",
   "eq1": "<span class=\"math\">t<sub>ij</sub> → t<sub>ij</sub> exp(i(e/ħ)∫<sub>j</sub><sup>i</sup> <b>A</b>·d<b>l</b>)</span>",
   "eqlabel2": "Flux per plaquette",
   "eq2": "<span class=\"math\">∏<sub>plaquette</sub> phases = exp(2πi Φ/Φ<sub>0</sub>),   Φ<sub>0</sub> = h/e</span>",
   "eqlabel3": "Harper equation (Landau gauge, <span class=\"math\">k<sub>x</sub></span> conserved)",
   "eq3": "<span class=\"math\">−t[ψ<sub>y+1</sub> + ψ<sub>y−1</sub>] − 2t cos(k<sub>x</sub>a − 2πα y) ψ<sub>y</sub> = E ψ<sub>y</sub>,   α = Φ/Φ<sub>0</sub></span>",
   "eqlabel4": "Rational flux",
   "eq4": "<span class=\"math\">α = p/q</span> ⇒ the magnetic unit cell is <span class=\"math\">q</span> sites and the band splits into <span class=\"math\">q</span> subbands",
   "notes": "The Harper equation is worth the board: a 1D chain with a cosine potential whose period is 1/α lattice spacings — commensurate for rational α. That is why the spectrum vs α is so intricate. Q: \"How does the notebook get a magnetic field into a lead?\" A: Landau gauge with A along the lead; the phases then depend on y only and the lead stays periodic in x."
  },
  "hofstadter": {
   "title": "The Hofstadter butterfly",
   "lead": "Spectrum of the square lattice against flux per plaquette: at every rational flux the band splits, and the gap structure recurs at every scale.",
   "b1": "Computed with <code>kwant.wraparound</code> at fixed denominator <span class=\"math\">q</span>: <span class=\"math\">q</span> magnetic subbands per flux value.",
   "b2": "Every gap carries an integer — its Hall conductance (TKNN, 1982) — the colour in the 3D view; the Landau fan of the previous slide is the sliver near <span class=\"math\">Φ = 0</span>.",
   "b3": "The first experiments to resolve it used moiré superlattices in graphene (2013), where the magnetic unit cell fits in a laboratory field.",
   "notes": "Spend a moment on the beauty; then on the content: every gap is a quantum Hall phase with its own integer, and the integers satisfy a Diophantine equation. The 3D coloured view is the notebook's own figure with Chern numbers from the same code used in section 8 — the deck's first topological invariant, planted early. Q: \"Why do we need moiré lattices to see it?\" A: one flux quantum per atomic plaquette would need ~10⁴ T; a superlattice of 10 nm needs a few tesla."
  },
  "figpage-31": {
   "title": "Figure 31 · Magnetic fields — Peierls substitution and Landau levels",
   "notes": "Figure 31 of the notebook (cell 44). The Hofstadter butterfly in 3D: the density of states as a landscape over (flux, energy), computed at fixed denominator q = 89. The wings of the butterfly appear as ridges of finite DOS and the nested hierarchy of gaps as canyons of exactly zero DOS; each canyon is a quantum Hall phase labelled by its own Chern number."
  },
  "landau-fan-bhz": {
   "title": "A field can switch a topological phase off",
   "lead": "The BHZ quantum spin Hall model in a magnetic field: the Landau fan, and the level crossing where quantum spin Hall becomes quantum Hall.",
   "b1": "The BHZ model (section 6 builds it from a continuum Hamiltonian) has helical edge states protected by time reversal.",
   "b2": "A magnetic field breaks time reversal; the two lowest Landau levels cross at a critical field and the edge states are gone.",
   "b3": "Same code path: Peierls phases on the BHZ hoppings, spectrum vs <span class=\"math\">B</span>.",
   "notes": "This slide is a preview of section 8 and a demonstration that magnetic fields are a probe of topology: the crossing is the transition. Q: \"What does the crossing look like in transport?\" A: the quantised 2e²/h edge conductance of the QSH phase collapses beyond the crossing."
  },
  "part-toolbox": {
   "kicker": "Part 7 of 10",
   "title": "Toolbox",
   "sub": "The parts of Kwant that make large or unusual problems tractable, and the pitfalls the notebook fell into so you need not.",
   "ag1": "Seeing the system: kwant.plot and kwant.plotter.map",
   "ag2": "Figure 20 · Visualisation",
   "ag3": "Figure 23 · Visualisation",
   "ag4": "Spectra without diagonalisation: the kernel polynomial method",
   "ag5": "From a continuum Hamiltonian to a lattice in one call",
   "ag6": "Figure 26 · kwant.continuum — symbolic Hamiltonians, discretised automatically",
   "ag7": "Figure 27 · kwant.continuum — symbolic Hamiltonians, discretised automatically",
   "ag8": "Figure 28 · kwant.continuum — symbolic Hamiltonians, discretised automatically",
   "ag9": "What actually costs time",
   "ag10": "Pitfalls the notebook hit so you do not have to",
   "notes": "Section opener. The parts of Kwant that make large or unusual problems tractable, and the pitfalls the notebook fell into so you need not. The agenda colours say what each slide is: plain language (grey), a figure (green), Kwant code (blue), the mathematics (pink). Say in one sentence where this stop sits on the course map, then move on."
  },
  "plotting": {
   "title": "Seeing the system: kwant.plot and kwant.plotter.map",
   "lead": "Styling by callables: colour by sublattice, size by wavefunction weight, or interpolate onto a heat map.",
   "b1": "<code>kwant.plot(syst, site_color=f, site_size=g, hop_lw=h)</code> — each argument may be a function of the site (Builder) or of the site index (finalized system).",
   "b2": "<code>kwant.plotter.map(fsyst, density)</code> interpolates a per-site quantity onto a continuous image.",
   "b3": "3D lattices render the same way (the zincblende example in the notebook, fig. 23).",
   "notes": "One trap the notebook documents and reported upstream: a site_color callable receives a Site for a Builder but an integer index for a finalized system. Mention it — it costs everyone an hour once. Q: \"Can I plot with something other than matplotlib?\" A: Kwant 1.5 has a plotly backend for interactive 3D; the notebook keeps matplotlib so it runs everywhere."
  },
  "figpage-20": {
   "title": "Figure 20 · Visualisation",
   "notes": "Figure 20 of the notebook (cell 32). Styling callables: honeycomb flake with sublattices in black/white and intra-sublattice bonds thinned."
  },
  "figpage-23": {
   "title": "Figure 23 · Visualisation",
   "notes": "Figure 23 of the notebook (cell 33). The same plotting call renders 3D: a zincblende cuboid with its two sublattices in red and green."
  },
  "kpm": {
   "title": "Spectra without diagonalisation: the kernel polynomial method",
   "lead": "Expand the density of states in Chebyshev polynomials of H; each moment costs one sparse matrix–vector product.",
   "b1": "<span class=\"math\">ρ(E) = (1/π√(1−E<sup>2</sup>)) [g<sub>0</sub>μ<sub>0</sub> + 2Σ<sub>n≥1</sub> g<sub>n</sub>μ<sub>n</sub>T<sub>n</sub>(E)],   μ<sub>n</sub> = Tr T<sub>n</sub>(H)</span>",
   "b2": "The trace is estimated with random vectors; the Jackson kernel <span class=\"math\">g<sub>n</sub></span> damps the Gibbs ringing.",
   "b3": "<code>kwant.kpm.SpectralDensity(fsyst)</code>: graphene's van Hove peaks at <span class=\"math\">|E| = t</span> and the linear pseudogap at the Dirac point, for 10<sup>4</sup>–10<sup>6</sup> sites.",
   "notes": "KPM is how you get a density of states for a million sites in a minute. The resolution is set by the number of moments; the noise by the number of random vectors. The second figure is the sublattice-resolved local DOS with a staggered potential — the A and B sublattices become spectrally different. Q: \"Does KPM give eigenvectors?\" A: no — densities, local densities, and (with kwant.kpm.Correlator) conductivities; for eigenvectors you diagonalise."
  },
  "continuum": {
   "title": "From a continuum Hamiltonian to a lattice in one call",
   "lead": "Write the k·p model as a string; kwant.continuum discretises it symbolically.",
   "b1": "This is the BHZ model of HgTe quantum wells; <code>discretize</code> applies the finite-difference rules of section 1 to every <span class=\"math\">k</span> automatically.",
   "b2": "The ribbon spectrum shows a Kramers pair of helical edge states crossing the inverted gap (fig. 26); the edge states are spin-polarised and counter-propagating (fig. 27).",
   "b3": "<code>kwant.continuum.lambdify</code> evaluates the continuum dispersion to check the lattice against it (fig. 28).",
   "code": "import kwant.continuum\nhamiltonian = &quot;&quot;&quot;\n    + C * identity(4) + M * kron(sigma_0, sigma_z)\n    - B * (k_x**2 + k_y**2) * kron(sigma_0, sigma_z)\n    - D * (k_x**2 + k_y**2) * kron(sigma_0, sigma_0)\n    + A * k_x * kron(sigma_z, sigma_x)\n    - A * k_y * kron(sigma_0, sigma_y)\n&quot;&quot;&quot;\na = 20                                   # lattice constant in nm\ntemplate = kwant.continuum.discretize(hamiltonian, grid=a)\nsyst.fill(template, shape, start)\n",
   "notes": "This is the fastest route from a paper to a simulation: copy the Hamiltonian, discretise, fill a shape. Say what can go wrong: a too-coarse grid changes the physics (fermion doubling for linear terms is handled by the symmetric difference, but the band structure is only right for ka ≪ 1). Q: \"What is k_x in the string?\" A: a symbol; discretize replaces k_x by −i∂_x and then by its finite-difference stencil, keeping matrices and constants where they are."
  },
  "figpage-26": {
   "title": "Figure 26 · kwant.continuum — symbolic Hamiltonians, discretised automatically",
   "notes": "Figure 26 of the notebook (cell 39). BHZ ribbon band structure: a Kramers pair of helical edge states crossing the inverted bulk gap - the quantum spin Hall effect."
  },
  "figpage-27": {
   "title": "Figure 27 · kwant.continuum — symbolic Hamiltonians, discretised automatically",
   "notes": "Figure 27 of the notebook (cell 40). The BHZ edge states are localised at the ribbon edges (left) and spin-polarised (right): opposite spins counter-propagate on the same edge."
  },
  "figpage-28": {
   "title": "Figure 28 · kwant.continuum — symbolic Hamiltonians, discretised automatically",
   "notes": "Figure 28 of the notebook (cell 41). Continuum BHZ dispersion evaluated with kwant.continuum.lambdify: the lattice model reproduces it faithfully near k=0."
  },
  "solvers": {
   "title": "What actually costs time",
   "lead": "One sparse solve per energy; the solver choice matters more than anything else you can tune.",
   "b1": "MUMPS (via <code>python-mumps</code>) is the fast default when installed: close to linear scaling with the number of sites for quasi-1D systems.",
   "b2": "SciPy's SuperLU is the fallback: the same answers, several times slower.",
   "b3": "Lead self-energies are computed once per energy per lead and cached — many leads are cheap, many energies are not.",
   "notes": "The figure is the notebook's timing of a scattering solve versus system size. Give the rule of thumb: width matters more than length (bandwidth of the sparse matrix). Q: \"Can I parallelise over energies?\" A: yes, with processes — and this is exactly where the next slide's pitfall lives."
  },
  "pitfalls": {
   "title": "Pitfalls the notebook hit so you do not have to",
   "lead": "Five things that went wrong while building this course, each with its check.",
   "b1": "<strong>MUMPS is not re-entrant.</strong> Calling <code>kwant.smatrix</code> from several threads with MUMPS installed crashes the interpreter with no traceback. Use processes, a serial loop, or the SuperLU solver in threads. (Reported upstream with a patch; <code>test_thread_safety.py</code> guards it.)",
   "b2": "<strong>numpy ≥ 2.5 breaks <code>kwant.physics.magnetic_gauge</code></strong> in Kwant 1.5.0 (fixed upstream, unreleased): pin <code>numpy&lt;2.5</code> or avoid the gauge helper.",
   "b3": "<strong>Energies inside a gap</strong> give zero propagating modes and a scattering matrix of size 0 — check <code>num_propagating</code> before dividing.",
   "b4": "<strong>Degenerate BdG pairs</strong> come out with run-dependent signs; compare <span class=\"math\">|E|</span>.",
   "b5": "<strong>Every result gets an identity check:</strong> unitarity, sum rule, particle–hole symmetry, current conservation, an invariant's quantisation — <code>assert</code> them.",
   "notes": "This is the slide people photograph. Tell the MUMPS story in two sentences: a parallel sweep cell killed the kernel with no message; the diagnosis took an afternoon and became a regression test and an upstream patch. The lesson generalises: in numerical physics, the assertion is the experiment's error bar. Q: \"How do I know MUMPS is being used?\" A: kwant.solvers.default reports it; the notebook's first cell prints the active solver."
  },
  "part-topo1d": {
   "kicker": "Part 8 of 10",
   "title": "Topology in one dimension",
   "sub": "Four one-dimensional models where an integer, computed from the bulk, predicts a state at the edge.",
   "ag1": "The SSH chain: the simplest topological insulator",
   "ag2": "Figure 37 · The SSH chain — the simplest topological insulator",
   "ag3": "Figure 38 · The SSH chain — the simplest topological insulator",
   "ag4": "Winding number and Zak phase",
   "ag5": "The Kitaev chain: split an electron in two",
   "ag6": "Figure 41 · The Kitaev chain — Majorana zero modes",
   "ag7": "Figure 42 · The Kitaev chain — Majorana zero modes",
   "ag8": "Majorana operators and the Z<sub>2</sub> invariant",
   "ag9": "The Majorana nanowire: Kitaev physics in a real device",
   "ag10": "Figure 43 · The Majorana nanowire — Kitaev physics in a real device",
   "ag11": "Figure 46 · The Majorana nanowire — Kitaev physics in a real device",
   "ag12": "The Thouless pump: a Chern number in (k, t)",
   "notes": "Section opener. Four one-dimensional models where an integer, computed from the bulk, predicts a state at the edge. The agenda colours say what each slide is: plain language (grey), a figure (green), Kwant code (blue), the mathematics (pink). Say in one sentence where this stop sits on the course map, then move on."
  },
  "ssh": {
   "title": "The SSH chain: the simplest topological insulator",
   "lead": "Two sites per cell, alternating hoppings. Whether the weak bond is inside or between cells decides if the ends carry zero-energy states.",
   "b1": "For <span class=\"math\">t<sub>1</sub> &lt; t<sub>2</sub></span> a doublet is pinned to zero energy for any chain length; for <span class=\"math\">t<sub>1</sub> &gt; t<sub>2</sub></span> there is none.",
   "b2": "The two zero modes live at opposite ends, each on a single sublattice (fig. 37); in-gap transport with weak leads happens only in the topological phase (fig. 38).",
   "b3": "Nothing local distinguishes the two phases — only a winding number of the bulk does.",
   "notes": "Start with the bond picture: a chain of dimers; cut it between strong bonds and you leave an unpaired site at each end. That is the whole intuition, and it is exact in the fully dimerised limit. The spectrum figure shows the zero-energy doublet appearing precisely at t1 = t2. Q: \"Are the zero modes protected?\" A: by chiral (sublattice) symmetry — a perturbation that respects it cannot move them from zero; the maths slide says why."
  },
  "figpage-37": {
   "title": "Figure 37 · The SSH chain — the simplest topological insulator",
   "notes": "Figure 37 of the notebook (cell 54). Probability density of the two zero modes: exponentially localised at the ends, each living on a single sublattice."
  },
  "figpage-38": {
   "title": "Figure 38 · The SSH chain — the simplest topological insulator",
   "notes": "Figure 38 of the notebook (cell 55). Transmission through a short SSH chain with weak leads (log scale): in-gap transport happens only in the topological phase, by resonant tunnelling through the hybridised edge doublet."
  },
  "ssh-math": {
   "title": "Winding number and Zak phase",
   "lead": "The bulk Hamiltonian is a vector in the plane; count how many times it winds around the origin.",
   "b1": "The notebook computes <span class=\"math\">ν</span> from <span class=\"math\"><b>d</b>(k)</span> and the Zak phase from the Bloch eigenvectors, and asserts they agree with the count of zero modes.",
   "b2": "Chiral symmetry keeps <span class=\"math\">d<sub>z</sub> = 0</span>: the loop cannot leave the plane, so the winding cannot change without closing the gap.",
   "eqlabel1": "Bloch Hamiltonian",
   "eq1": "<span class=\"math\">H(k) = <b>d</b>(k)·<b>σ</b>,   <b>d</b> = (t<sub>1</sub> + t<sub>2</sub>cos k,  t<sub>2</sub>sin k,  0)</span>",
   "eqlabel2": "Winding number",
   "eq2": "<span class=\"math\">ν = (1/2πi) ∮ dk  d<sub>k</sub> log(d<sub>x</sub> + i d<sub>y</sub>)  ∈ ℤ</span>",
   "eqlabel3": "Zak phase",
   "eq3": "<span class=\"math\">γ = i ∮ dk ⟨u<sub>k</sub>|∂<sub>k</sub>u<sub>k</sub>⟩ = πν  (mod 2π)</span>",
   "eqlabel4": "Bulk–boundary",
   "eq4": "<span class=\"math\">ν = 1</span> ⇒ one zero mode per end, protected by <span class=\"math\">σ<sub>z</sub>Hσ<sub>z</sub> = −H</span>",
   "notes": "Draw the d(k) circle: centre t1, radius t2 — it encloses the origin exactly when t2 > t1. That picture is the invariant. The Zak phase is its Berry-phase form and is what generalises to 2D. Q: \"What if the chiral symmetry is broken?\" A: the zero modes move off zero but stay at the ends as long as the gap is open; the topological classification changes (no integer, just a Berry phase)."
  },
  "kitaev": {
   "title": "The Kitaev chain: split an electron in two",
   "lead": "A p-wave superconducting chain. Each fermion is two Majorana operators; in the topological phase the unpaired Majoranas sit at the two ends.",
   "b1": "Topological for <span class=\"math\">|μ| &lt; 2t</span> with <span class=\"math\">Δ ≠ 0</span>: a zero-energy BdG state spans the whole window (fig. 40), its density split between the ends (fig. 41).",
   "b2": "The Majorana end mode pins the Andreev conductance at exactly <span class=\"math\">2e<sup>2</sup>/h</span> at zero bias, for any barrier (fig. 42).",
   "b3": "Two Majoranas far apart make one fermion whose occupation costs no energy — the qubit idea.",
   "notes": "The Majorana-language figure is the intuition: write c = (γ1 + iγ2)/2, choose parameters so the Hamiltonian couples γ2 of one site to γ1 of the next, and the first and last operators are left out. The zero-bias peak quantised at 2e²/h is the experimental signature everybody looks for. Q: \"How is this different from the SSH zero modes?\" A: these are their own antiparticles — a Majorana mode is half a fermion; SSH zero modes are ordinary electron states."
  },
  "figpage-41": {
   "title": "Figure 41 · The Kitaev chain — Majorana zero modes",
   "notes": "Figure 41 of the notebook (cell 58). Density of the near-zero state: one fermion split into two Majorana halves at opposite ends."
  },
  "figpage-42": {
   "title": "Figure 42 · The Kitaev chain — Majorana zero modes",
   "notes": "Figure 42 of the notebook (cell 59). Andreev conductance vs bias: the Majorana end mode pins a zero-bias peak at exactly 2e2/h, for any barrier strength; the trivial phase stays dark below the gap."
  },
  "kitaev-math": {
   "title": "Majorana operators and the Z<sub>2</sub> invariant",
   "lead": "The invariant of a particle–hole symmetric chain is a sign: the Pfaffian of the Hamiltonian at the two time-reversal-invariant momenta.",
   "b1": "The notebook computes the Pfaffians and asserts the phase boundary at <span class=\"math\">μ = ±2t</span>.",
   "b2": "A Z<sub>2</sub> invariant can only be 0 or 1: two Majorana pairs at one end can gap each other out.",
   "eqlabel1": "Kitaev Hamiltonian",
   "eq1": "<span class=\"math\">H = Σ<sub>j</sub> [−μ c<sup>†</sup><sub>j</sub>c<sub>j</sub> − t(c<sup>†</sup><sub>j</sub>c<sub>j+1</sub> + h.c.) + Δ(c<sub>j</sub>c<sub>j+1</sub> + h.c.)]</span>",
   "eqlabel2": "Majorana operators",
   "eq2": "<span class=\"math\">c<sub>j</sub> = (γ<sub>j,1</sub> + iγ<sub>j,2</sub>)/2,   γ<sup>†</sup> = γ,   {γ<sub>a</sub>, γ<sub>b</sub>} = 2δ<sub>ab</sub></span>",
   "eqlabel3": "Z<sub>2</sub> invariant",
   "eq3": "<span class=\"math\">(−1)<sup>ν</sup> = sgn Pf[A(0)] · sgn Pf[A(π)],   A(k) = i H<sub>BdG</sub>(k) </span> in the Majorana basis",
   "eqlabel4": "Result",
   "eq4": "<span class=\"math\">ν = 1 ⇔ |μ| &lt; 2t</span>",
   "notes": "The Pfaffian is the square root of the determinant with a sign; that sign is the invariant. Point at the two momenta 0 and π — the only ones where a 1D BdG Hamiltonian is its own particle–hole partner. Q: \"Why Z2 and not Z?\" A: particle–hole symmetry alone (class D) only protects the parity of the number of Majoranas per end."
  },
  "nanowire": {
   "title": "The Majorana nanowire: Kitaev physics in a real device",
   "lead": "A semiconductor wire with spin–orbit coupling on a superconductor, in a magnetic field. Three ingredients, one Kitaev chain.",
   "b1": "The bulk gap closes exactly at <span class=\"math\">B<sub>c</sub> = √(Δ<sup>2</sup> + μ<sup>2</sup>)</span> and reopens topological (fig. 44).",
   "b2": "A tunnelling map <span class=\"math\">G(V, B)</span> shows the zero-bias peak emerging beyond <span class=\"math\">B<sub>c</sub></span> (fig. 45); the Majorana pair is visible in real space (fig. 46).",
   "b3": "Rashba + Zeeman make the helical gap of section 4; proximity pairing inside it is effectively p-wave.",
   "notes": "This is the Oreg–Lutchyn / Lutchyn–Sau–Das Sarma proposal of 2010 and the device of the 2012 experiments. Say clearly what the notebook shows: the phase boundary formula reproduced numerically, and the zero-bias peak. Then say what it does not: disorder, soft gaps, Andreev bound states that mimic the peak — the reason the experiments are still debated. Q: \"Why do we need the magnetic field?\" A: to remove one spin species from the Fermi level so that the induced pairing is effectively spinless — the Kitaev condition."
  },
  "figpage-43": {
   "title": "Figure 43 · The Majorana nanowire — Kitaev physics in a real device",
   "notes": "Figure 43 of the notebook (cell 61). The Majorana nanowire device: a semiconductor wire with Rashba coupling α lies on an s-wave superconductor that proximity-induces Δ; a magnetic field B points along the wire, and a normal lead probes the end through a tunnel barrier. This is exactly the geometry of the simulated conductance map below and of the 2012 Delft experiment."
  },
  "figpage-46": {
   "title": "Figure 46 · The Majorana nanowire — Kitaev physics in a real device",
   "notes": "Figure 46 of the notebook (cell 62). The Majorana pair of the nanowire in real space: the lowest BdG eigenstate of a closed 120-site wire at B = 1.8 B_c is exponentially localized at the two ends and exponentially close to zero energy - the object whose tunnelling signature is the quantized zero-bias peak above."
  },
  "pump": {
   "title": "The Thouless pump: a Chern number in (k, t)",
   "lead": "Cycle the SSH parameters slowly around the gapless point and exactly one electron per cell is transported per cycle.",
   "b1": "The Rice–Mele model adds a staggered potential to SSH; the cycle encircles the only gapless point <span class=\"math\">(δ, Δ) = (0, 0)</span>.",
   "b2": "Edge states ladder across the bulk gap while the bulk polarisation winds by one unit cell (fig. 48).",
   "b3": "The pumped charge is the Chern number of the band over the <span class=\"math\">(k, t)</span> torus — the same integer as in 2D.",
   "notes": "This is the bridge to section 8: replace time by a second momentum and the pump becomes a Chern insulator. The notebook computes the Chern number with the same function it later uses for Haldane. Q: \"Has this been measured?\" A: yes — in cold-atom optical superlattices (2016) and in photonic waveguides."
  },
  "part-topo2d3d": {
   "kicker": "Part 9 of 10",
   "title": "Topology in two and three dimensions",
   "sub": "Six models, one method: compute a Berry-curvature invariant from the bulk Bloch Hamiltonian, then find the promised boundary state in a finite system.",
   "ag1": "The Haldane model: a Chern insulator without Landau levels",
   "ag2": "Figure 49 · The Haldane model — a Chern insulator without Landau levels",
   "ag3": "Berry curvature and the Chern number on a lattice",
   "ag4": "Figure 51 · The Haldane model — a Chern insulator without Landau levels",
   "ag5": "Kane–Mele: two copies of Haldane, one Z<sub>2</sub>",
   "ag6": "The p+ip superconductor: a chiral Majorana edge",
   "ag7": "Figure 55 · The p+ip superconductor — chiral Majorana edges",
   "ag8": "Figure 57 · The p+ip superconductor — chiral Majorana edges",
   "ag9": "Higher-order topology: the BBH quadrupole",
   "ag10": "Figure 59 · The BBH quadrupole — higher-order topology",
   "ag11": "Weyl semimetals: Fermi arcs from sliced Chern numbers",
   "ag12": "Figure 64 · Weyl semimetals — Fermi arcs from sliced Chern numbers",
   "ag13": "Figure 65 · Weyl semimetals — Fermi arcs from sliced Chern numbers",
   "ag14": "The 3D topological insulator: a Dirac cone on every surface",
   "ag15": "Figure 67 · The 3D topological insulator — a Dirac cone on every surface",
   "notes": "Section opener. Six models, one method: compute a Berry-curvature invariant from the bulk Bloch Hamiltonian, then find the promised boundary state in a finite system. The agenda colours say what each slide is: plain language (grey), a figure (green), Kwant code (blue), the mathematics (pink). Say in one sentence where this stop sits on the course map, then move on."
  },
  "haldane": {
   "title": "The Haldane model: a Chern insulator without Landau levels",
   "lead": "Honeycomb lattice, real nearest-neighbour hopping, complex second-neighbour hopping. A quantum Hall effect with zero net field.",
   "b1": "Phase diagram from the Chern number: lobes with <span class=\"math\">C = ±1</span> bounded by <span class=\"math\">|M| = 3√3 t<sub>2</sub> sin φ</span> (fig. 50).",
   "b2": "One chiral edge mode per edge crosses the bulk gap of a zigzag ribbon (fig. 52); the two-terminal conductance is <span class=\"math\">e<sup>2</sup>/h</span>.",
   "b3": "Realised in cold atoms (2014) and, as the quantum anomalous Hall effect, in magnetic topological insulators (2013).",
   "notes": "Haldane's 1988 paper is the origin of everything in this section. The figure of the lattice (fig. 49) shows the second-neighbour bonds with their phases; the phase diagram is computed by the notebook with the Fukui–Hatsugai–Suzuki method on a 30×30 grid. Q: \"Why does the net flux have to be zero?\" A: it need not — but with zero net flux the model keeps the lattice translation symmetry, which is the point: no Landau levels, still a Chern number."
  },
  "figpage-49": {
   "title": "Figure 49 · The Haldane model — a Chern insulator without Landau levels",
   "notes": "Figure 49 of the notebook (cell 67). The Haldane model on the honeycomb lattice (A blue, B red): real NN hopping plus complex second-neighbour hoppings t2 e± iφ, with the phase acquired along the arrowed (chiral) direction. This mimics a staggered magnetic flux with zero net flux per plaquette - time reversal is broken without any Landau levels. The Kane-Mele model of the next section uses the same lattice, with opposite chirality for opposite spins."
  },
  "chern-math": {
   "title": "Berry curvature and the Chern number on a lattice",
   "lead": "The invariant is the integral of the Berry curvature over the Brillouin-zone torus; on a grid it is a sum of plaquette phases.",
   "b1": "The lattice formula is gauge invariant plaquette by plaquette and exactly integer for any grid fine enough to resolve the gap — the notebook's <code>chern_fhs</code> (section 20) serves every 2D model.",
   "b2": "The Berry curvature of the lower Haldane band over the torus (fig. 51) integrates to <span class=\"math\">C = 1</span>.",
   "eqlabel1": "Berry connection and curvature",
   "eq1": "<span class=\"math\">A<sub>i</sub>(<b>k</b>) = i⟨u|∂<sub>i</sub>u⟩,   Ω = ∂<sub>x</sub>A<sub>y</sub> − ∂<sub>y</sub>A<sub>x</sub></span>",
   "eqlabel2": "Chern number",
   "eq2": "<span class=\"math\">C = (1/2π) ∫<sub>BZ</sub> Ω d<sup>2</sup>k  ∈ ℤ</span>",
   "eqlabel3": "Fukui–Hatsugai–Suzuki",
   "eq3": "<span class=\"math\">U<sub>i</sub>(<b>k</b>) = ⟨u<sub><b>k</b></sub>|u<sub><b>k</b>+δ<sub>i</sub></sub>⟩/|…|,   F = arg[U<sub>x</sub>(<b>k</b>) U<sub>y</sub>(<b>k</b>+δ<sub>x</sub>) U<sub>x</sub>(<b>k</b>+δ<sub>y</sub>)<sup>−1</sup> U<sub>y</sub>(<b>k</b>)<sup>−1</sup>],   C = (1/2π)Σ F</span>",
   "eqlabel4": "TKNN",
   "eq4": "<span class=\"math\">σ<sub>xy</sub> = (e<sup>2</sup>/h) Σ<sub>occupied</sub> C<sub>n</sub></span>",
   "notes": "Derive the FHS link variable on the board: it is the discrete version of the Berry phase around one plaquette; the sum of all plaquettes is the Chern number because the phases of interior links cancel. Stress 'from the system': the notebook takes H(k) from the Kwant Builder via wraparound, so any model you build can be tested. Q: \"How fine a grid?\" A: the notebook's chern_fhs defaults to 40×40 and the result is exactly integer on any grid that resolves the gap; near a phase transition the curvature spikes and you need more."
  },
  "figpage-51": {
   "title": "Figure 51 · The Haldane model — a Chern insulator without Landau levels",
   "notes": "Figure 51 of the notebook (cell 69). Berry curvature of the lower Haldane band over the Brillouin-zone torus (reduced coordinates; the two bumps sit at the Dirac points K and Kprime). In the topological phase (left) both valleys carry curvature of the same sign and the surface integrates to exactly 2pi - Chern number 1. In the trivial phase (right) the staggered mass has re-inverted one valley: a tall negative spike at Kprime (whose gap is small, hence the large curvature) exactly cancels the broad positive lobe at K, and the integral vanishes. The Chern number is nothing but the signed volume under this surface."
  },
  "kane-mele": {
   "title": "Kane–Mele: two copies of Haldane, one Z<sub>2</sub>",
   "lead": "Spin-up and spin-down electrons see opposite Haldane phases. Time reversal is restored; the edge carries a helical pair.",
   "b1": "The helical crossing survives Rashba coupling because Kramers' theorem forbids the two partners from mixing (fig. 53, right).",
   "b2": "All current injected inside the gap flows along the edges (fig. 54); the two-terminal conductance is <span class=\"math\">2e<sup>2</sup>/h</span>.",
   "b3": "The invariant is Z<sub>2</sub>: the spin Chern number mod 2, or the Fu–Kane Pfaffian.",
   "notes": "The quantum spin Hall effect: HgTe wells (2007) are the BHZ version of this; Kane–Mele is the graphene version with a spin–orbit gap too small to see. The key protection statement is Kramers: at time-reversal-invariant momenta the two edge states are a Kramers pair and cannot split. Q: \"What is a Z2 invariant physically?\" A: whether the number of Kramers pairs of edge states is odd (protected) or even (can be gapped out)."
  },
  "pip": {
   "title": "The p+ip superconductor: a chiral Majorana edge",
   "lead": "Spinless pairing with a phase that winds around the Fermi surface. The topological phase has a single Majorana mode running around the boundary.",
   "b1": "BdG Chern number <span class=\"math\">C = ±1</span> in the weak-pairing phases, transitions at <span class=\"math\">μ = 0, ±4t</span> (fig. 56).",
   "b2": "A strip has one chiral Majorana branch crossing the gap in the topological phase (fig. 57); a finite sample's lowest state circulates the whole boundary (fig. 58).",
   "b3": "A vortex in the pairing binds a Majorana zero mode — the 2D route to non-Abelian statistics.",
   "notes": "This is the 2D Kitaev chain and the effective model of the ν = 5/2 quantum Hall state and of Sr₂RuO₄ (disputed). The pairing is real on horizontal bonds and imaginary on vertical ones (fig. 55) — that is the phase winding on the lattice. Q: \"Chiral Majorana — half a chiral fermion?\" A: yes: it carries half the thermal Hall conductance of an electron edge mode, κ = ½ × (π²k_B²T/3h)."
  },
  "figpage-55": {
   "title": "Figure 55 · The p+ip superconductor — chiral Majorana edges",
   "notes": "Figure 55 of the notebook (cell 74). The p+ip pairing on the square lattice: the pair potential is real on horizontal bonds and imaginary on vertical ones, so its phase winds by 2π around the Fermi surface - the lattice version of Δ(k)∝ kx + i ky. This winding is what makes the BdG bands carry a Chern number."
  },
  "figpage-57": {
   "title": "Figure 57 · The p+ip superconductor — chiral Majorana edges",
   "notes": "Figure 57 of the notebook (cell 75). Strip spectra: a single chiral Majorana branch crosses the gap in the topological phase (left); the trivial phase is fully gapped (right)."
  },
  "bbh": {
   "title": "Higher-order topology: the BBH quadrupole",
   "lead": "Four sites per cell on a square lattice with π flux. The bulk and the edges are gapped; the corners carry the zero modes.",
   "b1": "Wannier bands <span class=\"math\">ν<sub>±</sub>(k<sub>x</sub>)</span> are gapped in the topological phase and collapse in the trivial one (fig. 60).",
   "b2": "A finite flake has four zero-energy states whose density sits on the four corners (fig. 61); each carries charge <span class=\"math\">e/2</span>.",
   "b3": "The invariant is a nested Wilson loop — a Berry phase of a Berry phase — the quadrupole moment quantised to ½.",
   "notes": "Benalcazar–Bernevig–Hughes 2017; realised in microwave, acoustic and electrical-circuit metamaterials within a year. The point for the course: the boundary of the boundary carries the state — a second-order insulator. Q: \"Why π flux?\" A: it makes the model have the mirror and C4 symmetries with the right algebra to quantise the quadrupole; the notebook implements it as a sign on one bond per plaquette."
  },
  "figpage-59": {
   "title": "Figure 59 · The BBH quadrupole — higher-order topology",
   "notes": "Figure 59 of the notebook (cell 77). The BBH lattice: four sites per unit cell with weak intra-cell bonds γ (thin) and strong inter-cell bonds λ (thick). One bond of every square carries a minus sign (red dashed), threading a π flux through each plaquette; this flux gaps the would-be edge bands, so for γ the protected zero modes are pushed all the way to the corners."
  },
  "weyl": {
   "title": "Weyl semimetals: Fermi arcs from sliced Chern numbers",
   "lead": "A 3D band touching that is a monopole of Berry curvature. Slice the Brillouin zone: the Chern number jumps at each node, and the surface shows an arc.",
   "b1": "Chern number of the 2D slices <span class=\"math\">H(k<sub>x</sub>, k<sub>y</sub>; k<sub>z</sub>)</span> jumps by the chirality <span class=\"math\">±1</span> at each Weyl node (fig. 62).",
   "b2": "Between the nodes every slice is a Chern insulator with an edge state — stacked, they form the <strong>Fermi arc</strong> on the surface (fig. 63).",
   "b3": "Transport through a Weyl bar (fig. 65) shows the arc contribution; the 3D dispersion (fig. 64) shows the two sheets touching at the nodes.",
   "notes": "The slicing argument is the whole physics: a 3D semimetal is a family of 2D insulators parametrised by k_z, and the Chern number can only change where the gap closes — at a Weyl node. Discovered in TaAs in 2015. Q: \"Can Weyl nodes be removed?\" A: only by annihilating two of opposite chirality — the monopole charge is conserved."
  },
  "figpage-64": {
   "title": "Figure 64 · Weyl semimetals — Fermi arcs from sliced Chern numbers",
   "notes": "Figure 64 of the notebook (cell 80). The Weyl slab dispersion in 3D: the two bands nearest E=0 over the surface Brillouin zone. The sheets touch at the projections of the two Weyl nodes (stars) - the remnants of the bulk cones - and, unlike the point-touching Dirac cone of the 3D TI, they stay glued together along a whole line segment between them (cyan): the Fermi arc. The arc is the stack of chiral edge modes of all the C=1 slices found above."
  },
  "figpage-65": {
   "title": "Figure 65 · Weyl semimetals — Fermi arcs from sliced Chern numbers",
   "notes": "Figure 65 of the notebook (cell 80). Geometry of the Weyl transport bar: an 8x8x6 cubic-lattice block (blue) with semi-infinite leads (red) along z, the direction joining the two Weyl nodes."
  },
  "ti3d": {
   "title": "The 3D topological insulator: a Dirac cone on every surface",
   "lead": "A band-inverted 3D insulator with time reversal. Its Z<sub>2</sub> index is a product of parities; its surface is a single, unremovable Dirac cone.",
   "b1": "Slab spectrum coloured by surface weight: one surface Dirac cone spans the inverted gap (fig. 66); as a 3D dispersion it is a single cone (fig. 67).",
   "b2": "Fu–Kane: <span class=\"math\">(−1)<sup>ν<sub>0</sub></sup> = ∏<sub>TRIM</sub> ξ<sub>occupied</sub></span> — the product of parity eigenvalues at the eight time-reversal-invariant momenta.",
   "b3": "Transport through a TI bar (fig. 68): in the topological phase the surface conducts while the bulk is insulating.",
   "notes": "Bi₂Se₃ is the textbook material; the notebook's model is the four-band k·p lattice model. The single Dirac cone is the odd number that Z2 protects — a normal surface state comes in pairs. Q: \"Why can a single Dirac cone not exist in a 2D lattice by itself?\" A: fermion doubling — on a 2D lattice cones come in pairs; a single one needs the 3D bulk as its 'other half'. That is why a TI surface is different from graphene."
  },
  "figpage-67": {
   "title": "Figure 67 · The 3D topological insulator — a Dirac cone on every surface",
   "notes": "Figure 67 of the notebook (cell 82). The protected surface state of the strong TI as a 3D dispersion: the two slab bands nearest E=0 form a single Dirac cone centred at the surface Gamma point, with velocity set by the SOC strength. Away from the node the sheets bend over as they merge into the bulk bands. A single cone like this cannot exist in any standalone 2D lattice (fermion doubling) - it lives only on the boundary of a 3D topological bulk."
  },
  "part-close": {
   "kicker": "Part 10 of 10",
   "title": "Close",
   "sub": "Send them to the notebook: how to run it, what the exercises ask, where to read next.",
   "ag1": "Run it yourself",
   "ag2": "The exercises",
   "ag3": "Where to read next",
   "ag4": "Thank you",
   "notes": "Section opener. Send them to the notebook: how to run it, what the exercises ask, where to read next. The agenda colours say what each slide is: plain language (grey), a figure (green), Kwant code (blue), the mathematics (pink). Say in one sentence where this stop sits on the course map, then move on."
  },
  "run-it": {
   "title": "Run it yourself",
   "lead": "One command on Windows; three lines of conda elsewhere. Then Run All.",
   "b1": "Open <code>Kwant_Theory_and_Practice.ipynb</code> with the kernel <strong>Python (kwant)</strong> and Run All: about four minutes with MUMPS.",
   "b2": "Every figure of this deck is a numbered figure of that notebook (<code>course/figures/figures.json</code> maps them).",
   "b3": "<code>python -m pytest tests</code> checks the notebook's counts, the licence texts and the documentation.",
   "code": "# Windows (PowerShell, from the repository):\n.\\install_kwant_windows.ps1        # Miniforge + kwant + MUMPS + kernel &#x27;kwant&#x27;\npython verify_kwant.py             # ends with &#x27;physically correct&#x27;\n\n# Linux / macOS / existing conda:\nconda create -n kwant -c conda-forge kwant &quot;numpy&lt;2.5&quot; scipy matplotlib sympy python-mumps ipykernel jupyterlab\nconda activate kwant\npython -m ipykernel install --user --name kwant --display-name &quot;Python (kwant)&quot;\n",
   "notes": "Do the install before the lecture, not during. The verify script runs real physics checks — quantised conductance, unitarity, the sum rule — so 'it imports' is not the bar. Q: \"pip install kwant?\" A: on Linux it works; on Windows the conda-forge build is the one with MUMPS and is the one this course was tested with."
  },
  "exercises": {
   "title": "The exercises",
   "lead": "Twenty-five, at the end of each part, each with an origin flag and a difficulty mark; every one is solved and asserted in the companion notebook.",
   "b1": "◦ direct — one call or one parameter change: thread a wire (E1.1), sweep the potential well (E1.4), reverse the Rice–Mele pump cycle (E2.5), recompute the Haldane phase diagram (E2.6).",
   "b2": "• requires thought — a new observable or geometry: the Landauer formula at finite bias (E1.3), universal conductance fluctuations (E1.5), the graphene p–n sweep (E1.6), a Kane–Mele Rashba sweep (E2.8), tracking the Weyl nodes (E2.11).",
   "b3": "★ mini-project — Andreev bound states and the Josephson effect (E1.8), a next-nearest-neighbour SSH chain (E2.3), a vortex in the p+ip superconductor (E2.9), the Fu–Kane parity invariant (E2.12).",
   "b4": "Two are pencil-and-paper: the FHS plaquette flux (E1.11) and what particle–hole symmetry alone implies (E2.14).",
   "b5": "Origins are marked: some are re-posed Kwant tutorial problems, some paraphrase topocondmat.org or Asbóth <em>et al.</em>, most are original. The solutions notebook is the marking key: its <code>assert</code>s are the rubric.",
   "notes": "Assign by mark: ◦ for everyone, • for a problem set, ★ for a term project. The assert-based solutions mean students can self-check without seeing the code first — hide the solutions notebook until the deadline. Q: \"Can I use the solutions in my own course?\" A: yes — Apache-2.0; keep the notice and the attribution cell."
  },
  "reading": {
   "title": "Where to read next",
   "lead": "The three sources this course was modelled on, and the papers behind each model.",
   "b1": "<strong>Kwant</strong>: Groth, Wimmer, Akhmerov, Waintal, <em>New J. Phys.</em> 16, 063065 (2014); the tutorial at kwant-project.org.",
   "b2": "<strong>Transport</strong>: Datta, <em>Electronic Transport in Mesoscopic Systems</em>; Nazarov & Blanter, <em>Quantum Transport</em>.",
   "b3": "<strong>Topology</strong>: Asbóth, Oroszlány, Pályi, <em>A Short Course on Topological Insulators</em> (arXiv:1509.02295); topocondmat.org (TU Delft); Bernevig & Hughes, <em>Topological Insulators and Topological Superconductors</em>.",
   "b4": "<strong>The models</strong>: SSH 1979 · Haldane 1988 · Kane–Mele 2005 · Fu–Kane 2007 · Kitaev 2001 · Lutchyn/Oreg 2010 · BBH 2017 · Weyl in TaAs 2015 — every one cited in the notebook's reference shelf (section 27).",
   "b5": "<strong>Upstream</strong>: the Kwant findings of this project (MUMPS re-entrancy, numpy 2.5, plotter warning filters) are documented in <code>docs/02-findings-backlog.md</code> with patches.",
   "notes": "Point students at the notebook's section 27, which has ~70 references with one-line descriptions, rather than at this slide. Q: \"Is there a textbook that uses Kwant throughout?\" A: topocondmat.org is the closest; this notebook was written to be that for a transport course."
  },
  "thanks": {
   "kicker": "Quantum Transport with Kwant",
   "title": "Thank you",
   "sub": "Slides, handout, lecturer notes and the notebook that made every figure: kwant-theory-and-practice · Apache-2.0",
   "notes": "Close by returning to the object on the table: the steps in the current are e²/h, the Majorana peak is 2e²/h, the Chern number is an integer — and the notebook checks all three. The handout has the reference card, the key equations and the models table. Q: \"Where do I report a problem?\" A: the repository's issue tracker; the notebook's counts and figures are tested, so a failing test is a real finding."
  }
 }
};
